function dp = DAR_PART(IL, IR, field, WL, WR, W0, W1, WNzm1, WNz, ...
    coeff_2_d_3_m_SQRDT_m_SQRTKAPPA, coeff_1i_m_C0_m_SQRDZ_d_dt, kappa, ...
    coeff_exp_CL_m_dt_m_kappa, coeff_exp_CR_m_dt_m_kappa, C1, C2, Nz)

Nzm1 = Nz - 1;

D_0_PART =   C1 * (IL + coeff_2_d_3_m_SQRDT_m_SQRTKAPPA * (W0 * field(1)...
    + W1 * field(2) + WL) * coeff_exp_CL_m_dt_m_kappa);
D_MIDDLE_PART = 2.0D0 * (kappa - coeff_1i_m_C0_m_SQRDZ_d_dt) .* field(2:Nzm1)...
    - kappa * (field(1:Nz - 2) + field(3:Nz));
D_END_PART = - C2 * (IR + coeff_2_d_3_m_SQRDT_m_SQRTKAPPA * (WNzm1 * field(Nzm1)...
    + WNz * field(Nz) + WR) * coeff_exp_CR_m_dt_m_kappa);

dp = [D_0_PART; D_MIDDLE_PART; D_END_PART];

% D_0_PART =   C1 * (IL + coeff_2_d_3_m_SQRDT * (W0 * field(1)...
%     + W1 * field(2) + WL(IDX(step-1))) * coeff_exp_CL_m_dt);
% D_MIDDLE_PART = 2.0D0 * (1.0D0 - coeff_1i_m_C0_m_SQRDZ_d_dt) .* field(2:Nzm1)...
%     - (field(1:Nz - 2) + field(3:Nz));
% D_END_PART = - C2 * (IR + coeff_2_d_3_m_SQRDT * (WNzm1 * field(Nzm1)...
%     + WNz * field(Nz) + WR(IDX(step-1))) * coeff_exp_CR_m_dt);
end