function S = Sigma(f1, f2, j1, j2, Sold, coeff_1i_m_C0_d_3_d_dt_d_kappa, coeff_1i_d_6)

S = -(-coeff_1i_m_C0_d_3_d_dt_d_kappa) * f1 ...
    + (-coeff_1i_m_C0_d_3_d_dt_d_kappa) * f2 ...
    -coeff_1i_d_6*(j1 + j2) - Sold;

% Sigma0(IDX(step)) = -(-coeff_1i_m_C0_d_3_d_dt) * field(1) ...
%     + (-coeff_1i_m_C0_d_3_d_dt) * F0(IDX(step - 1)) ...
%     -coeff_1i_d_6*(cu(1) + J0(IDX(step - 1))) - Sigma0(IDX(step - 1));
% Sigma1(IDX(step)) = -(-coeff_1i_m_C0_d_3_d_dt) * field(2) ...
%     + (-coeff_1i_m_C0_d_3_d_dt) * F1(IDX(step - 1)) ...
%     -coeff_1i_d_6*(cu(2) + J1(IDX(step - 1))) - Sigma1(IDX(step - 1));
% 
% SigmaNz(IDX(step)) = -(-coeff_1i_m_C0_d_3_d_dt) * field(Nz) ...
%     + (-coeff_1i_m_C0_d_3_d_dt) * FNz(IDX(step - 1)) ...
%     -coeff_1i_d_6*(cu(Nz) + JNz(IDX(step - 1))) - SigmaNz(IDX(step - 1));
% SigmaNzm1(IDX(step)) = -(-coeff_1i_m_C0_d_3_d_dt) * field(Nzm1) ...
%     + (-coeff_1i_m_C0_d_3_d_dt) * FNzm1(IDX(step - 1)) ...
%     -coeff_1i_d_6*(cu(Nzm1) + JNzm1(IDX(step - 1))) - SigmaNzm1(IDX(step - 1));
end